### Import Library

In [ ]:
import pandas as pd

### Import data tipe csv

In [ ]:
df = pd.read_csv('Data Alumni.csv')
df

,No,Nim,Nama,Tempat & tanggal lahir,Fakultas/Ketrampilan,Alamat,Tahun Masuk,Tahun Lulus,Status Pekerjaan,Lama Masa Tunggu (bulan),Gaji Pertama bekerjaa,Nilai Toefl,IPK
0,1,9018263,Puguh Drajat E.P,"Purworejo, 4 November 1989",FTI / Teknik Iformatika,Tangerang Rt. 01/ 0,2009,2016,NaN,2.4,1475635.0,390.0,"2,13"
1,2,12022030,Arsyad Cahya Subrata,"Bantul, 21 juni 1994",FTI / Teknik Elektro,"Karangpule Rt.01 , Tirtonirmolo , Kasihan Bantul",2012,2016,NaN,NaN,NaN,NaN,NaN
2,3,12020021,Yesi Novela,"Tempilang, 1 januari 1995",FTI,NaN,2012,2016,Mahasiswa,2.4,1475635.0,NaN,NaN
3,4,9018269,Pandu Herwijaya,"Lampung, 19 Desember 1990",FTI/ Teknik Infomatika,"Tamantirto, Kasihan ,Bantul",2009,2016,NaN,2.4,1475634.0,413.0,"2,75"
4,5,9018109,Anjar Prasetyo,"Gunungkidul, 27 April 1991",FTI /Teknik Informatika,"Umbulharjo , Yogyakarta",2009,2016,NaN,NaN,NaN,NaN,NaN
5,6,9020026,Moh. Dadi Kurniawan,"Savanajaya, 27 Maret 1992",FTI / Futsal,Saren Rt. 02 Rw. 01 Caturtunggal,2009,2016,NaN,2.4,1475635.0,400.0,"3,24"
6,7,12018060,Martin Sarlina,"Lepak, 23 Maret 1994",FTI,NTB,2012,2016,NaN,2.4,1475635.0,396.0,"3,27"
7,8,11018022,Yan Adhi Permadi,"Jepara, 22 juni 1993",FTI,Umbulharjo V,2011,2016,Wiraswasta,2.4,1475635.0,460.0,"3,20"
8,9,9018212,Achicha Wahyuni,"Yogyakarta, 3 juni 1991",FTI/ Web Design,"Noyokerten, Sendangirto, Berbah",2009,2016,Guru,0.0,600000.0,403.0,"3,24"
9,10,9018301,Yayan Tisna Permadi,"Purbalingga, 08 Oktober 1991",FTI/ Teknik Inormatika,"Tajug, Rt.04/ 05 Purbalingga",2009,2016,NaN,2.4,1475635.0,450.0,"3,06"
10,11,12022020,Muh. Rama dhai,"Pekanbaru, 29 Maret 1992",FTI / Teknik Elektro,"Karongan Rt/Rw. 04/11 Jogotirto, Berbah Sleman",2012,2016,NaN,2.4,1200000.0,423.0,3.47
11,12,12022038,Nurwahyuddi,"Dili, timor-timur/ 13 April 1995",FTI / Teknik Elektro,Juru Gentong J V/407 C Banguntapan,2012,2016,Mahasiswa,2.4,1475635.0,413.0,"3,62"
12,13,12019039,Agus Purnomo,"Klaten, 2 Agustus 1992",FTI/ Teknik Industri,"Dukuh Glagahwangi, Polanharjo",2012,2016,NaN,2.4,1475635.0,480.0,"3,32"
13,14,11018111,M. Akhwan Zulfayandi,"Teros, 12 September 1992",FTI/ Teknik Informatika,"Jl. Peumnas gg. Indragiri Blok B/24, Condongcatur",2011,2016,NaN,2.4,1475635.0,406.0,"3,14"
14,15,9018135,Yunita Tri Hernawai,"Magelang, 20 Juni 1991",FTI/ Teknik Informatika,Magelang,2009,2016,Swasta,1.0,1500000.0,423.0,"2,99"
15,16,12018161,Pratama Setya Aji,"Sleman, 20 September 1994",FTI,Jl. Affandi gg.Kamboja CTX.19 Yogyakarta,2012,2016,Freelance,0.0,750000.0,400.0,"3,60"

### Cek tipe data per baris

In [ ]:
df.dtypes

No                            int64
Nim                           int64
Nama                         object
Tempat & tanggal lahir       object
Fakultas/Ketrampilan         object
Alamat                       object
Tahun Masuk                   int64
Tahun Lulus                   int64
Status Pekerjaan             object
Lama Masa Tunggu (bulan)    float64
Gaji Pertama bekerjaa       float64
Nilai Toefl                 float64
IPK                          object
dtype: object

In [ ]:
df.columns = ['No','NIM','Nama','TTL','Fakultas','Alamat','Masuk','Lulus','Status','MasaTunggu','Gaji','TOEFL','IPK']
df['IPK'] = df['IPK'].str.replace(",",".").astype(float)
df

,No,NIM,Nama,TTL,Fakultas,Alamat,Masuk,Lulus,Status,MasaTunggu,Gaji,TOEFL,IPK
0,1,9018263,Puguh Drajat E.P,"Purworejo, 4 November 1989",FTI / Teknik Iformatika,Tangerang Rt. 01/ 0,2009,2016,NaN,2.4,1475635.0,390.0,2.13
1,2,12022030,Arsyad Cahya Subrata,"Bantul, 21 juni 1994",FTI / Teknik Elektro,"Karangpule Rt.01 , Tirtonirmolo , Kasihan Bantul",2012,2016,NaN,NaN,NaN,NaN,NaN
2,3,12020021,Yesi Novela,"Tempilang, 1 januari 1995",FTI,NaN,2012,2016,Mahasiswa,2.4,1475635.0,NaN,NaN
3,4,9018269,Pandu Herwijaya,"Lampung, 19 Desember 1990",FTI/ Teknik Infomatika,"Tamantirto, Kasihan ,Bantul",2009,2016,NaN,2.4,1475634.0,413.0,2.75
4,5,9018109,Anjar Prasetyo,"Gunungkidul, 27 April 1991",FTI /Teknik Informatika,"Umbulharjo , Yogyakarta",2009,2016,NaN,NaN,NaN,NaN,NaN
5,6,9020026,Moh. Dadi Kurniawan,"Savanajaya, 27 Maret 1992",FTI / Futsal,Saren Rt. 02 Rw. 01 Caturtunggal,2009,2016,NaN,2.4,1475635.0,400.0,3.24
6,7,12018060,Martin Sarlina,"Lepak, 23 Maret 1994",FTI,NTB,2012,2016,NaN,2.4,1475635.0,396.0,3.27
7,8,11018022,Yan Adhi Permadi,"Jepara, 22 juni 1993",FTI,Umbulharjo V,2011,2016,Wiraswasta,2.4,1475635.0,460.0,3.20
8,9,9018212,Achicha Wahyuni,"Yogyakarta, 3 juni 1991",FTI/ Web Design,"Noyokerten, Sendangirto, Berbah",2009,2016,Guru,0.0,600000.0,403.0,3.24
9,10,9018301,Yayan Tisna Permadi,"Purbalingga, 08 Oktober 1991",FTI/ Teknik Inormatika,"Tajug, Rt.04/ 05 Purbalingga",2009,2016,NaN,2.4,1475635.0,450.0,3.06
10,11,12022020,Muh. Rama dhai,"Pekanbaru, 29 Maret 1992",FTI / Teknik Elektro,"Karongan Rt/Rw. 04/11 Jogotirto, Berbah Sleman",2012,2016,NaN,2.4,1200000.0,423.0,3.47
11,12,12022038,Nurwahyuddi,"Dili, timor-timur/ 13 April 1995",FTI / Teknik Elektro,Juru Gentong J V/407 C Banguntapan,2012,2016,Mahasiswa,2.4,1475635.0,413.0,3.62
12,13,12019039,Agus Purnomo,"Klaten, 2 Agustus 1992",FTI/ Teknik Industri,"Dukuh Glagahwangi, Polanharjo",2012,2016,NaN,2.4,1475635.0,480.0,3.32
13,14,11018111,M. Akhwan Zulfayandi,"Teros, 12 September 1992",FTI/ Teknik Informatika,"Jl. Peumnas gg. Indragiri Blok B/24, Condongcatur",2011,2016,NaN,2.4,1475635.0,406.0,3.14
14,15,9018135,Yunita Tri Hernawai,"Magelang, 20 Juni 1991",FTI/ Teknik Informatika,Magelang,2009,2016,Swasta,1.0,1500000.0,423.0,2.99
15,16,12018161,Pratama Setya Aji,"Sleman, 20 September 1994",FTI,Jl. Affandi gg.Kamboja CTX.19 Yogyakarta,2012,2016,Freelance,0.0,750000.0,400.0,3.60

In [ ]:
df.isna().sum()

No             0
NIM            0
Nama           0
TTL            0
Fakultas       0
Alamat         1
Masuk          0
Lulus          0
Status        10
MasaTunggu     2
Gaji           2
TOEFL          3
IPK            3
dtype: int64

### Mean Value

In [ ]:
mean_IPK = df.IPK.mean()
mean_TOEFL = df.TOEFL.mean()
mean_Masa = df.MasaTunggu.mean()

In [ ]:
mean_IPK

3.1561538461538463

In [ ]:
mean_TOEFL

419.7692307692308

In [ ]:
mean_Masa

1.9571428571428569

In [ ]:
df.IPK.fillna(mean_IPK, inplace=True)
df.TOEFL.fillna(mean_TOEFL, inplace=True)
df.MasaTunggu.fillna(mean_Masa, inplace=True)
df

,No,NIM,Nama,TTL,Fakultas,Alamat,Masuk,Lulus,Status,MasaTunggu,Gaji,TOEFL,IPK
0,1,9018263,Puguh Drajat E.P,"Purworejo, 4 November 1989",FTI / Teknik Iformatika,Tangerang Rt. 01/ 0,2009,2016,NaN,2.400000,1475635.0,390.000000,2.130000
1,2,12022030,Arsyad Cahya Subrata,"Bantul, 21 juni 1994",FTI / Teknik Elektro,"Karangpule Rt.01 , Tirtonirmolo , Kasihan Bantul",2012,2016,NaN,1.957143,NaN,419.769231,3.156154
2,3,12020021,Yesi Novela,"Tempilang, 1 januari 1995",FTI,NaN,2012,2016,Mahasiswa,2.400000,1475635.0,419.769231,3.156154
3,4,9018269,Pandu Herwijaya,"Lampung, 19 Desember 1990",FTI/ Teknik Infomatika,"Tamantirto, Kasihan ,Bantul",2009,2016,NaN,2.400000,1475634.0,413.000000,2.750000
4,5,9018109,Anjar Prasetyo,"Gunungkidul, 27 April 1991",FTI /Teknik Informatika,"Umbulharjo , Yogyakarta",2009,2016,NaN,1.957143,NaN,419.769231,3.156154
5,6,9020026,Moh. Dadi Kurniawan,"Savanajaya, 27 Maret 1992",FTI / Futsal,Saren Rt. 02 Rw. 01 Caturtunggal,2009,2016,NaN,2.400000,1475635.0,400.000000,3.240000
6,7,12018060,Martin Sarlina,"Lepak, 23 Maret 1994",FTI,NTB,2012,2016,NaN,2.400000,1475635.0,396.000000,3.270000
7,8,11018022,Yan Adhi Permadi,"Jepara, 22 juni 1993",FTI,Umbulharjo V,2011,2016,Wiraswasta,2.400000,1475635.0,460.000000,3.200000
8,9,9018212,Achicha Wahyuni,"Yogyakarta, 3 juni 1991",FTI/ Web Design,"Noyokerten, Sendangirto, Berbah",2009,2016,Guru,0.000000,600000.0,403.000000,3.240000
9,10,9018301,Yayan Tisna Permadi,"Purbalingga, 08 Oktober 1991",FTI/ Teknik Inormatika,"Tajug, Rt.04/ 05 Purbalingga",2009,2016,NaN,2.400000,1475635.0,450.000000,3.060000
10,11,12022020,Muh. Rama dhai,"Pekanbaru, 29 Maret 1992",FTI / Teknik Elektro,"Karongan Rt/Rw. 04/11 Jogotirto, Berbah Sleman",2012,2016,NaN,2.400000,1200000.0,423.000000,3.470000
11,12,12022038,Nurwahyuddi,"Dili, timor-timur/ 13 April 1995",FTI / Teknik Elektro,Juru Gentong J V/407 C Banguntapan,2012,2016,Mahasiswa,2.400000,1475635.0,413.000000,3.620000
12,13,12019039,Agus Purnomo,"Klaten, 2 Agustus 1992",FTI/ Teknik Industri,"Dukuh Glagahwangi, Polanharjo",2012,2016,NaN,2.400000,1475635.0,480.000000,3.320000
13,14,11018111,M. Akhwan Zulfayandi,"Teros, 12 September 1992",FTI/ Teknik Informatika,"Jl. Peumnas gg. Indragiri Blok B/24, Condongcatur",2011,2016,NaN,2.400000,1475635.0,406.000000,3.140000
14,15,9018135,Yunita Tri Hernawai,"Magelang, 20 Juni 1991",FTI/ Teknik Informatika,Magelang,2009,2016,Swasta,1.000000,1500000.0,423.000000,2.990000
15,16,12018161,Pratama Setya Aji,"Sleman, 20 September 1994",FTI,Jl. Affandi gg.Kamboja CTX.19 Yogyakarta,2012,2016,Freelance,0.000000,750000.0,400.000000,3.600000

In [ ]:
def_status = "Mahasiswa"
df.Status.fillna(def_status, inplace =True)
df

,No,NIM,Nama,TTL,Fakultas,Alamat,Masuk,Lulus,Status,MasaTunggu,Gaji,TOEFL,IPK
0,1,9018263,Puguh Drajat E.P,"Purworejo, 4 November 1989",FTI / Teknik Iformatika,Tangerang Rt. 01/ 0,2009,2016,Mahasiswa,2.400000,1475635.0,390.000000,2.130000
1,2,12022030,Arsyad Cahya Subrata,"Bantul, 21 juni 1994",FTI / Teknik Elektro,"Karangpule Rt.01 , Tirtonirmolo , Kasihan Bantul",2012,2016,Mahasiswa,1.957143,NaN,419.769231,3.156154
2,3,12020021,Yesi Novela,"Tempilang, 1 januari 1995",FTI,NaN,2012,2016,Mahasiswa,2.400000,1475635.0,419.769231,3.156154
3,4,9018269,Pandu Herwijaya,"Lampung, 19 Desember 1990",FTI/ Teknik Infomatika,"Tamantirto, Kasihan ,Bantul",2009,2016,Mahasiswa,2.400000,1475634.0,413.000000,2.750000
4,5,9018109,Anjar Prasetyo,"Gunungkidul, 27 April 1991",FTI /Teknik Informatika,"Umbulharjo , Yogyakarta",2009,2016,Mahasiswa,1.957143,NaN,419.769231,3.156154
5,6,9020026,Moh. Dadi Kurniawan,"Savanajaya, 27 Maret 1992",FTI / Futsal,Saren Rt. 02 Rw. 01 Caturtunggal,2009,2016,Mahasiswa,2.400000,1475635.0,400.000000,3.240000
6,7,12018060,Martin Sarlina,"Lepak, 23 Maret 1994",FTI,NTB,2012,2016,Mahasiswa,2.400000,1475635.0,396.000000,3.270000
7,8,11018022,Yan Adhi Permadi,"Jepara, 22 juni 1993",FTI,Umbulharjo V,2011,2016,Wiraswasta,2.400000,1475635.0,460.000000,3.200000
8,9,9018212,Achicha Wahyuni,"Yogyakarta, 3 juni 1991",FTI/ Web Design,"Noyokerten, Sendangirto, Berbah",2009,2016,Guru,0.000000,600000.0,403.000000,3.240000
9,10,9018301,Yayan Tisna Permadi,"Purbalingga, 08 Oktober 1991",FTI/ Teknik Inormatika,"Tajug, Rt.04/ 05 Purbalingga",2009,2016,Mahasiswa,2.400000,1475635.0,450.000000,3.060000
10,11,12022020,Muh. Rama dhai,"Pekanbaru, 29 Maret 1992",FTI / Teknik Elektro,"Karongan Rt/Rw. 04/11 Jogotirto, Berbah Sleman",2012,2016,Mahasiswa,2.400000,1200000.0,423.000000,3.470000
11,12,12022038,Nurwahyuddi,"Dili, timor-timur/ 13 April 1995",FTI / Teknik Elektro,Juru Gentong J V/407 C Banguntapan,2012,2016,Mahasiswa,2.400000,1475635.0,413.000000,3.620000
12,13,12019039,Agus Purnomo,"Klaten, 2 Agustus 1992",FTI/ Teknik Industri,"Dukuh Glagahwangi, Polanharjo",2012,2016,Mahasiswa,2.400000,1475635.0,480.000000,3.320000
13,14,11018111,M. Akhwan Zulfayandi,"Teros, 12 September 1992",FTI/ Teknik Informatika,"Jl. Peumnas gg. Indragiri Blok B/24, Condongcatur",2011,2016,Mahasiswa,2.400000,1475635.0,406.000000,3.140000
14,15,9018135,Yunita Tri Hernawai,"Magelang, 20 Juni 1991",FTI/ Teknik Informatika,Magelang,2009,2016,Swasta,1.000000,1500000.0,423.000000,2.990000
15,16,12018161,Pratama Setya Aji,"Sleman, 20 September 1994",FTI,Jl. Affandi gg.Kamboja CTX.19 Yogyakarta,2012,2016,Freelance,0.000000,750000.0,400.000000,3.600000

In [ ]:
df.isna().sum()

No            0
NIM           0
Nama          0
TTL           0
Fakultas      0
Alamat        1
Masuk         0
Lulus         0
Status        0
MasaTunggu    0
Gaji          2
TOEFL         0
IPK           0
dtype: int64

### Don't Care Method

In [ ]:
def_alamat = "-"
df.Alamat.fillna(def_alamat, inplace =True)
def_gaji = "0"
df.Gaji.fillna(def_gaji, inplace =True)
df

,No,NIM,Nama,TTL,Fakultas,Alamat,Masuk,Lulus,Status,MasaTunggu,Gaji,TOEFL,IPK
0,1,9018263,Puguh Drajat E.P,"Purworejo, 4 November 1989",FTI / Teknik Iformatika,Tangerang Rt. 01/ 0,2009,2016,Mahasiswa,2.400000,1475635.0,390.000000,2.130000
1,2,12022030,Arsyad Cahya Subrata,"Bantul, 21 juni 1994",FTI / Teknik Elektro,"Karangpule Rt.01 , Tirtonirmolo , Kasihan Bantul",2012,2016,Mahasiswa,1.957143,0,419.769231,3.156154
2,3,12020021,Yesi Novela,"Tempilang, 1 januari 1995",FTI,-,2012,2016,Mahasiswa,2.400000,1475635.0,419.769231,3.156154
3,4,9018269,Pandu Herwijaya,"Lampung, 19 Desember 1990",FTI/ Teknik Infomatika,"Tamantirto, Kasihan ,Bantul",2009,2016,Mahasiswa,2.400000,1475634.0,413.000000,2.750000
4,5,9018109,Anjar Prasetyo,"Gunungkidul, 27 April 1991",FTI /Teknik Informatika,"Umbulharjo , Yogyakarta",2009,2016,Mahasiswa,1.957143,0,419.769231,3.156154
5,6,9020026,Moh. Dadi Kurniawan,"Savanajaya, 27 Maret 1992",FTI / Futsal,Saren Rt. 02 Rw. 01 Caturtunggal,2009,2016,Mahasiswa,2.400000,1475635.0,400.000000,3.240000
6,7,12018060,Martin Sarlina,"Lepak, 23 Maret 1994",FTI,NTB,2012,2016,Mahasiswa,2.400000,1475635.0,396.000000,3.270000
7,8,11018022,Yan Adhi Permadi,"Jepara, 22 juni 1993",FTI,Umbulharjo V,2011,2016,Wiraswasta,2.400000,1475635.0,460.000000,3.200000
8,9,9018212,Achicha Wahyuni,"Yogyakarta, 3 juni 1991",FTI/ Web Design,"Noyokerten, Sendangirto, Berbah",2009,2016,Guru,0.000000,600000.0,403.000000,3.240000
9,10,9018301,Yayan Tisna Permadi,"Purbalingga, 08 Oktober 1991",FTI/ Teknik Inormatika,"Tajug, Rt.04/ 05 Purbalingga",2009,2016,Mahasiswa,2.400000,1475635.0,450.000000,3.060000
10,11,12022020,Muh. Rama dhai,"Pekanbaru, 29 Maret 1992",FTI / Teknik Elektro,"Karongan Rt/Rw. 04/11 Jogotirto, Berbah Sleman",2012,2016,Mahasiswa,2.400000,1200000.0,423.000000,3.470000
11,12,12022038,Nurwahyuddi,"Dili, timor-timur/ 13 April 1995",FTI / Teknik Elektro,Juru Gentong J V/407 C Banguntapan,2012,2016,Mahasiswa,2.400000,1475635.0,413.000000,3.620000
12,13,12019039,Agus Purnomo,"Klaten, 2 Agustus 1992",FTI/ Teknik Industri,"Dukuh Glagahwangi, Polanharjo",2012,2016,Mahasiswa,2.400000,1475635.0,480.000000,3.320000
13,14,11018111,M. Akhwan Zulfayandi,"Teros, 12 September 1992",FTI/ Teknik Informatika,"Jl. Peumnas gg. Indragiri Blok B/24, Condongcatur",2011,2016,Mahasiswa,2.400000,1475635.0,406.000000,3.140000
14,15,9018135,Yunita Tri Hernawai,"Magelang, 20 Juni 1991",FTI/ Teknik Informatika,Magelang,2009,2016,Swasta,1.000000,1500000.0,423.000000,2.990000
15,16,12018161,Pratama Setya Aji,"Sleman, 20 September 1994",FTI,Jl. Affandi gg.Kamboja CTX.19 Yogyakarta,2012,2016,Freelance,0.000000,750000.0,400.000000,3.600000

In [ ]:
df.isna().sum()

No            0
NIM           0
Nama          0
TTL           0
Fakultas      0
Alamat        0
Masuk         0
Lulus         0
Status        0
MasaTunggu    0
Gaji          0
TOEFL         0
IPK           0
dtype: int64

### Detecting Outlier

In [ ]:
import statistics
from statistics import stdev

In [ ]:
std_IPK = (statistics.stdev(df.IPK))
std_IPK

0.348473594629272

In [ ]:
T_IPK_max = mean_IPK + (2*std_IPK)
T_IPK_min = mean_IPK - (2*std_IPK)

In [ ]:
T_IPK_max

3.8531010354123905

In [ ]:
T_IPK_min

2.459206656895302